baseURL = "https://josephbales.com/"
languageCode = "en-us"
title = "josephbales.com"
theme = "personal"
summaryLength = 30

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 20
  [[menu.main]]
    name = "Bio"
    url = "/bio/"
    weight = 30
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 40

[params]
  author = "Joseph Bales"
  description = "random thoughts & stuff"
