baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'josephbales.com'
theme = 'personal'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 20
  [[menu.main]]
    name = "Bio"
    url = "/bio/"
    weight = 30
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 40

[params]
  author = "Your Name"
  description = "random thoughts & stuff"
